ViewComponents/RoomViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ChatApp.Database;
using ChatApp.Models;
using System.Linq;
using System;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
namespace ChatApp.ViewComponents
{
    public class RoomViewComponent :ViewComponent//ViewComponent is similar to Components in Angular
    {
        private ApplicationDbContext _db;
        public RoomViewComponent(ApplicationDbContext db)
        {
            // Console.BackgroundColor = ConsoleColor.Green;
            Console.WriteLine("Room Componenet has been called");
            _db = db;
        }
        public IViewComponentResult Invoke(){
            var chats = new List<Chat>();
            if(HttpContext.User.Identity.IsAuthenticated){
                var userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                // var chats = _db.Chats.ToList();//ToList is present in System.Linq
                 chats  = _db.ChatUsers
                            .Include(x => x.Chat)
                            .Where(x => x.UserId==userId)
                            .Select(x=>x.Chat)
                            .ToList();
                
               
            }
            return View(chats);
            
            
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Chating App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css">
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-info main-navbar">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Chating App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
   
  </div>
</nav>
<div class="d-flex flex-row justify-content-start main-container">
    <div class="sidenavbar d-flex flex-column justify-content-start">
        <div class="btn btn-primary btn-menu">
            Home
        </div>
        <vc:room></vc:room> 
        @* room is a componenet and vc is meant for View Component *@
        <button type="button"  class="btn btn-primary btn-menu" data-bs-toggle="modal"data-bs-target="#exampleModal">
            +
        </button>
        <a type="button" class="btn btn-danger btn-menu" asp-controller="Account" asp-action="Logout">Logout</a>
    </div>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            
            @RenderBody()
        </main>
    </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Enter Room</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <form asp-controller="Home" asp-action="CreateRoom" method="post">
        <input type="text" name="RoomName"  id="" placeholder="Enter the room Id">
          <button type="submit" class="btn btn-primary">Join</button>
      </form>
 
      </div>
     
    </div>
  </div>
</div>
    
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["title"]</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
    
</head>
<body>
    @*the main boy of the inner html will be Rendered here *@
    @RenderBody()
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>

</html>